### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [reconquest/orgalorg#1]
First of all, thanks for sharing a nice software!

Could you add LICENSE file?
The following page may help for choosing a license.
[Choose an open source license - Choose a License](http://choosealicense.com/)

I hope you choose a permissive license like MIT or Apache v2.
Thanks!

**Comment by seletskiy** [comment]
@hnakamur: thanks for the feedback. I've added MIT license to the source code.

**Comment by hnakamur** [comment]
@seletskiy Thanks! :+1:

**Comment by seletskiy** [comment]
@hnakamur: Do you use it?

**Comment by hnakamur** [comment]
Not yet. I need to check the license before using it.
