### ISSUE TITLE
can't acquire lock, lock already obtained by another process or unavailable

### ISSUE THREAD

**Issue by kxjhlele** [reconquest/orgalorg#17]
orgalorg -u big -p -o 192.168.6.204 -o 192.168.6.206 -o 192.168.6.208 -i ls.script -C bash > ls.log

ls.script:  cd /home/cbss/20161129/ && ls

2016-11-29 09:27:35 [FATAL] connecting to cluster failed
                            └─ connection to 3 of 3 nodes failed
                               └─ can't connect to nodes
                                  ├─ [richuser@111.222.6.204:22] can't acquire lock, lock already obtained by another process or unavailable
                                  ├─ [richuser@111.222.6.208:22] can't acquire lock, lock already obtained by another process or unavailable
                                  └─ [richuser@111.222.6.206:22] can't acquire lock, lock already obtained by another process or unavailable

**Comment by seletskiy** [comment]
@kxjhlele: Try running with `-vv` options. Also, you can skip lock phase altogether by using `--no-lock`.

**Comment by kxjhlele** [comment]
thx,

 running lock command
                            └─ [sh -c flock -nx / -c 'printf "acquired\n" && cat' || printf "locked\n"]
 {flock} <stderr> flock: cannot open lock file /: Is a directory

**Comment by seletskiy** [comment]
@kxjhlele: `orgalorg` uses host's `flock`, and your looks too old, because it do not supports locking directories. So, either update `flock` on host or use `--no-lock` flag.
