### ISSUE TITLE
Windows 10 error: undefined: syscall.Stat_t

### ISSUE THREAD

**Issue by kxjhlele** [reconquest/orgalorg#19]
system: windows 10
golang 1.7.4

# github.com/reconquest/orgalorg
D:\Home\Go\src\github.com\reconquest\orgalorg\archive.go:190: undefined: syscall.Stat_t
D:\Home\Go\src\github.com\reconquest\orgalorg\archive.go:197: undefined: syscall.Stat_t
D:\Home\Go\src\github.com\reconquest\orgalorg\archive.go:201: undefined: syscall.Stat_t

**Comment by kovetskiy** [comment]
Windows is not supported now. Pull-requests are welcome.
