### ISSUE TITLE
ssh: must specify HostKeyCallback error

### ISSUE THREAD

**Issue by linuxbsdfreak** [reconquest/orgalorg#20]
Hi,

I created the latest binary of orgalorg and got the error 

ssh: must specify HostKeyCallback when connecting

Is this a bug?

Regards,
Kevin

**Comment by kovetskiy** [comment]
Hi, thank you for the report.

I think it is introduced in third-party library in this commit:
https://github.com/theairkit/runcmd/commit/21ac0eb3b8e859d3c2049a38986bf7180ca1a4e3

And yes, it is bug, it will be fixed as soon as possible.

**Comment by linuxbsdfreak** [comment]
Verified with the latest and works now.

**Comment by kovetskiy** [comment]
@linuxbsdfreak thanks!
