### ISSUE TITLE
Simplify / document build process

### ISSUE THREAD

**Issue by mpenning** [reconquest/orgalorg#28]
Hi,

I've got the orgalorg-1.0 source on OSX Catalina... I'm trying to build and this seems a little challenging.  Is there a way to rip out the `reconquest/go-test.bash` and `reconquest/test-runnner` dependencies as a requirement just to install locally?  Another option would be more clear documentation about getting dependencies to build orgalorg.

```
(py38_osx) mpenning@MPENNING-M-PB3W orgalorg-1.0 % make
Makefile:5: vendor/github.com/reconquest/test-runner.bash/Makefile: No such file or directory
Makefile:6: vendor/github.com/reconquest/go-test.bash/Makefile: No such file or directory
bash -c 'source vendor/github.com/reconquest/import.bash/import.bash && \
		import "github.com/reconquest/go-test.bash"'
bash: vendor/github.com/reconquest/import.bash/import.bash: No such file or directory
make: *** [vendor/github.com/reconquest/go-test.bash/Makefile] Error 1
(py38_osx) mpenning@MPENNING-M-PB3W orgalorg-1.0 %
```

I exported GOROOT="" and GOPATH="~/go"... I extracted the source tarball in ~/ when I tried installing.

**Comment by kovetskiy** [comment]
@mpenning Hey there, thanks for the interest in orgalorg.

Please check the latest commit and `make build` command. The problem was that back in the day there was no conflict of interest in the `vendor` dir. Now the Go compiler is more dogmatic on what should be in the vendor directory.

**Comment by kovetskiy** [comment]
Also, I've just added mac to our goreleaser, you should see a new release and a build for mac.

**Comment by mpenning** [comment]
> Also, I've just added mac to our goreleaser, you should see a new release and a build for mac.

Great, I opened a follow-up PR #29 asking for some tweaks... this is mostly going to solve things.  Closing this PR.
