### ISSUE TITLE
Homebrew suggestion

### ISSUE THREAD

**Issue by arren-ru** [reconquest/orgalorg#30]
Hi guys, long time ago I've created homebrew files but only for personal usage and now found releases.
So, I would like to suggest https://github.com/arren-ru/homebrew-orgalorg

**Comment by seletskiy** [comment]
Hello, thanks for your contribution.

However, I'm not sure what action is required from our side?

**Comment by arren-ru** [comment]
Sorry for delay. I wanted to kindly suggest to create repository on your account for this homebrew file, but occasionally changed my mind and decided, that better decision for me is to contribute it to homebrew-core repository.
So, might be there is no action required from your side and now this issue is for people who wants to install it via brew.
Anyway thanks for great tool, very useful piece of software.

**Comment by seletskiy** [comment]
@arren-ru No problems and thanks for the kind words.

I'll leave this issue open for other people who use Homebrew. Feel free to close this issue when your contribution to the `homebrew-core` will be merged.

**Comment by arren-ru** [comment]
Somehow I managed to find the time for this https://github.com/Homebrew/homebrew-core/pull/73725
So, guys, we just waiting for PR being accepted and later I could maintain updates in Homebrew more quicker

**Comment by kovetskiy** [comment]
@arren-ru that's awesome, thank you!

**Comment by arren-ru** [comment]
Guys, we are done! Orgalorg is now in official Homebrew and bottled
```
❯ brew info orgalorg
orgalorg: stable 1.0.1 (bottled), HEAD
Parallel SSH commands executioner and file synchronization tool
https://github.com/reconquest/orgalorg
/usr/local/Cellar/orgalorg/1.0.1 (5 files, 5.5MB) *
  Poured from bottle on 2021-03-25 at 14:24:42
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/orgalorg.rb
License: MIT
```
