### ISSUE TITLE
Taking commands from file or STDIN doesnt return.

### ISSUE THREAD

**Issue by 0xtavian** [reconquest/orgalorg#31]
Hi all, first off thank you very much for this killer tool. 

When using `--stdin` or `-i`, after the last command has executed the terminal never returns. I have to control+c to close the process. Is this expected behavior? I built from source via `go get github.com/reconquest/orgalorg` go version go1.16.3 linux/amd64 on Ubuntu 20.04. Thank You in Advance!
```
root@localhost:~# cat commands.txt 
echo "first command executed"
echo "second command executed"
echo "This is the last command in the file"

root@localhost:~# orgalorg -q -o hosts -i commands.txt -C /bin/bash
op@localhost:~$ first command executed
op@localhost:~$ second command executed
op@localhost:~$ first command executed
op@localhost:~$ second command executed
op@localhost:~$ This is the last command in the file
op@localhost:~$ This is the last command in the file
op@localhost:~$ first command executed
op@localhost:~$ second command executed
op@localhost:~$ This is the last command in the file

^C
root@localhost:~# 
```

and with the ` -l` or `--serial` the first node never finishes so the second node and so-on are never invoked 
```
root@localhost:~# orgalorg -l -q -o hosts -i commands.txt -C /bin/bash
op@localhost:~$ first command executed
op@localhost:~$ second command executed
op@localhost:~$ This is the last command in the file
```

**Comment by kovetskiy** [comment]
hey there, should be fine now, could you check the master branch?

**Comment by 0xtavian** [comment]
@kovetskiy awesome! works fantastic now :).
Closing this issue.
