### ISSUE TITLE
Project description change suggestion

### ISSUE THREAD

**Issue by cr1cr1** [reconquest/orgalorg#36]
Hi guys,

I really like this tool, basically helped me ditch ansible and makeshift bash scripts to accomplish the same thing.
File synchronization is a great bonus.

What I'm about to say is .. trivial and superficial, I know. I just noticed something funny in the project description: "Parallel SSH commands `executioner` and file synchronization tool".
Unfortunately, `executioner` is exclusively someone that kills... well, people :) and has no context in IT.

I would recommend `Parallel SSH commands runner`.

**Comment by kovetskiy** [comment]
Thanks! I've just fixed it.
