### ISSUE TITLE
Consul inventory support

### ISSUE THREAD

**Issue by sokoow** [reconquest/orgalorg#8]
It'd be really cool for the tool to be able to operate on consul inventory groups. To explain, here's what I currently do with ansible (pretty much same functionality):

```
ansible -i consul_dynamic_inventory.rb wiki -s -m command -a 'uptime'
```

This is going to consul using the ruby file and unrolling my "wiki" server group. Then it uses ansible's command plugin to fire uptime via ssh. Consul has a cool advantage of adding/removing services ad-hoc. 

Here's how to get that information from Consul API:

```
#!/usr/bin/env ruby

require 'net/http'
require 'uri'
require 'json'

output = {}
s_json = JSON.parse(Net::HTTP.get_response(URI.parse('http://localhost:8500/v1/catalog/services')).body)
services = s_json.keys.reject{|k| k == 'consul'}
services.each do |srv|
  res = Net::HTTP.get_response(URI.parse("http://localhost:8500/v1/catalog/service/#{srv}")).body
  json = JSON.parse(res)
  a = []
  json.each {|j| a << j['Address'] }
  output = output.merge({srv => a})
end

puts JSON.generate(output)
```

It should be trivial to add this using golang, unfortunately I don't speak go yet :/ Sorry :)

**Comment by kovetskiy** [comment]
@sokoow **orgalorg** can read hosts from stdin, use flag `-s` for this, it will be something like:
```
ruby consul_dynamic_inventory.rb | orgalorg -s -p -u -C uptime
```

**Comment by seletskiy** [comment]
@sokoow: I agree with @kovetskiy on that point. `orgalorg` follows unix-way and should not care where data is coming from. It will happily accept hosts list from any source if you just pipe in on the stdin.
